name: Build and Security Check

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Application Image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout DevOps repository
        uses: actions/checkout@v5

      - name: Checkout application repository
        uses: actions/checkout@v5
        with:
          repository: Azmeth23/project-starwing-dev 
          path: application

      - name: Check application files
        run: |
          echo "Current directory:"
          pwd
          echo "Workspace:"
          ls -la
          echo "Application directory:"
          ls -la application
          echo "Application files:"
          find application -maxdepth 2 -type f

      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile \
            -t devops-kickstarter:1.0 \
            application

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.32.0
        with:
          image-ref: devops-kickstarter:1.0
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Action pushing the image to Docker Hub
        run: |
          docker push azmeth07/devops-kickstarter:1.0
