name: Build and Security Check

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Application Image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout DevOps repository
        uses: actions/checkout@v5

      - name: Checkout application repository
        uses: actions/checkout@v5
        with:
          repository: Azmeth23/project-starwing-devops-repo 
          path: application

      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile \
            -t devops-kickstarter:1.0 \
            application

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: devops-kickstarter:1.0
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH